#######################################
# Travis CI script
#######################################

language: python
sudo: required
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
    - pip install -r requirements.txt
script:
    - nosetests --with-coverage --cover-erase --cover-inclusive --cover-package=../../tellurium --cover-html







